# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enlace', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=20)),
                ('semilla', models.URLField()),
                ('pais', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('patron', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='enlace',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='googleCS.Patron'),
        ),
    ]
