# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleCS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='contenidoAyer',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='contenidoHoy',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
