# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleCS', '0002_auto_20160616_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='contenidoAyer',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='contenidoHoy',
            field=models.FileField(upload_to=''),
        ),
    ]
