# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import googleCS.models


class Migration(migrations.Migration):

    dependencies = [
        ('googleCS', '0003_auto_20160616_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='contenidoAyer',
            field=models.FileField(upload_to=googleCS.models.Contenido.url),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='contenidoHoy',
            field=models.FileField(upload_to=googleCS.models.Contenido.url),
        ),
    ]
