# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('categoriaPadre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaEnlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enlace', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=20)),
                ('semilla', models.URLField()),
                ('pais', models.CharField(max_length=20)),
                ('patron', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Patrones',
            },
        ),
        migrations.AddField(
            model_name='enlace',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Patron'),
        ),
        migrations.AddField(
            model_name='categoriaenlace',
            name='enlace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Enlace'),
        ),
    ]
