# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import search.models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('categoriaPadre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaEnlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Categoria')),
                ('enlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Enlace')),
            ],
        ),
        migrations.AlterField(
            model_name='contenido',
            name='contenidoAyer',
            field=models.FileField(max_length=200, upload_to=search.models.Contenido.url),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='contenidoHoy',
            field=models.FileField(max_length=200, upload_to=search.models.Contenido.url),
        ),
    ]
