# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20160712_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patron',
            name='ciudad',
        ),
    ]
